# Generated by Django 6.0.3 on 2026-03-22 19:38

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("mrn", models.CharField(db_index=True, max_length=50, unique=True)),
                ("is_high_priority", models.BooleanField(default=False)),
                ("spi_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "patients",
                "indexes": [
                    models.Index(fields=["created_at"], name="patients_created_b2d3e4_idx"),
                    models.Index(
                        fields=["last_name", "first_name"],
                        name="patients_last_na_ce6411_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recorded_at", models.DateTimeField()),
                ("heart_rate", models.IntegerField(blank=True, null=True)),
                ("respiratory_rate", models.IntegerField(blank=True, null=True)),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("spo2", models.IntegerField(blank=True, null=True)),
                ("systolic_bp", models.IntegerField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="monitoring.patient",
                    ),
                ),
            ],
            options={
                "db_table": "observations",
                "indexes": [
                    models.Index(
                        fields=["patient", "-recorded_at"],
                        name="observation_patient_96a1d6_idx",
                    ),
                    models.Index(
                        fields=["recorded_at"], name="observation_recorde_cd6acc_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("heart_rate__gte", 20), ("heart_rate__lte", 300)),
                            ("heart_rate__isnull", True),
                            _connector="OR",
                        ),
                        name="heart_rate_valid_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("respiratory_rate__gte", 5),
                                ("respiratory_rate__lte", 80),
                            ),
                            ("respiratory_rate__isnull", True),
                            _connector="OR",
                        ),
                        name="respiratory_rate_valid_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("temperature__gte", 25), ("temperature__lte", 45)),
                            ("temperature__isnull", True),
                            _connector="OR",
                        ),
                        name="temperature_valid_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("spo2__gte", 0), ("spo2__lte", 100)),
                            ("spo2__isnull", True),
                            _connector="OR",
                        ),
                        name="spo2_valid_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("systolic_bp__gte", 40), ("systolic_bp__lte", 300)),
                            ("systolic_bp__isnull", True),
                            _connector="OR",
                        ),
                        name="systolic_bp_valid_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("model", models.CharField(max_length=100)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="monitoring.patient",
                    ),
                ),
            ],
            options={
                "db_table": "devices",
                "indexes": [
                    models.Index(fields=["assigned_at"], name="devices_assigne_1e0498_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("assigned_at__isnull", True),
                                ("assigned_patient__isnull", True),
                            ),
                            models.Q(
                                ("assigned_at__isnull", False),
                                ("assigned_patient__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="device_assignment_timestamp_consistency",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("HIGH_HEART_RATE", "High heart rate"),
                            ("HIGH_TEMPERATURE", "High temperature"),
                            ("LOW_SPO2", "Low SpO2"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("SEVERE", "Severe"), ("MILD", "Mild")], max_length=50
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="monitoring.patient",
                    ),
                ),
            ],
            options={
                "db_table": "alerts",
                "indexes": [
                    models.Index(
                        fields=["patient", "is_active", "severity", "created_at"],
                        name="alerts_patient_5c1f88_idx",
                    ),
                    models.Index(fields=["created_at"], name="alerts_created_965da5_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("patient", "type"),
                        name="unique_active_alert_per_patient_and_type",
                    )
                ],
            },
        ),
    ]
